name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2 ] # Uses 2 parallel instances
        node-version: [ 16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
#          build: npm run build
          start: npm run



#        env:
#          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
#          # in GitHub repo → Settings → Secrets → Actions
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}